

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/biz_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: pass123

#dubbo配置
dubbo:
  application:
    name: dubbo-provider
    registry: zookeeper://47.104.241.41:2181

mybatis:
  mapper-locations: classpath*:mappers/*.xml

